@SistemaRh.api_HostAddress = http://localhost:5048

GET {{SistemaRh.api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{SistemaRh.api_HostAddress}}/api/funcionario
Content-Type: application/json

{
  "nome": "Douglas Silvestre",
  "cargo": "Auxiliar Administrativo",
  "dataAdmissao": "2025-08-23T07:39:55",
  "salario": 2500.00,
  "ativo": true
}

###

GET {{SistemaRh.api_HostAddress}}/api/funcionario
Accept: application/json
###


