@SistemaRh.api_HostAddress = http://localhost:5048

GET {{SistemaRh.api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{SistemaRh.api_HostAddress}}/api/funcionario
Content-Type: application/json

{
  "nome": "Iran Virgilio dos Santos",
  "cargo": "Desenvolvedor Pleno",
  "dataAdmissao": "2026-02-02T10:00:00",
  "salario": 4500.00,
  "ativo": true
}

###

POST {{SistemaRh.api_HostAddress}}/api/funcionario
Content-Type: application/json

{
  //Funcionario
}

###
