@SistemaRh.api_HostAddress = http://localhost:5048

GET {{SistemaRh.api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{SistemaRh.api_HostAddress}}/api/funcionario
Content-Type: application/json

{
  "nome": "Yure Gabriel dos Santos",
  "cargo": "Auxiliar Administrativo",
  "dataAdmissao": "2025-07-19T07:39:55",
  "salario": 2500.00,
  "ativo": true
}

###

GET {{SistemaRh.api_HostAddress}}/api/funcionario
Accept: application/json
###



GET {{SistemaRh.api_HostAddress}}/api/funcionario

###

@id=0
PUT {{SistemaRh.api_HostAddress}}/api/funcionario/1
Content-Type: application/json

{
  "nome": "Iran Virgilio dos Santos",
  "cargo": "Desenvolvedor Sênior",
  "dataAdmissao": "2026-02-02T10:00:00",
  "salario": 8500.00,
  "ativo": true
}

###

PUT {{SistemaRh.api_HostAddress}}/api/funcionario/5
Content-Type: application/json

{
  "nome": "Douglas Silvestre",
  "cargo": "Gerente",
  "salario": 4000.00,
  "ativo": true
}

###

DELETE {{SistemaRh.api_HostAddress}}/api/funcionario/6

###

POST {{SistemaRh.api_HostAddress}}/api/funcionario
Content-Type: application/json

{
  
  "nome": "X",
  "cargo": "",
  "dataAdmissao": "2026-02-02T10:00:00",
  "salario": -150.00,
  "ativo": true
}

###
